//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//
package team_wallstreet.wallstreet;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.Toast;

import team_wallstreet.wallstreet.HttpReq.CookieHelper;
import team_wallstreet.wallstreet.HttpReq.RequestListener;
import team_wallstreet.wallstreet.HttpReq.RequestManager;

/**
 * Splash Activity is the start-up activity that appears until a delay is expired
 * or the user taps the screen.  When the splash activity starts, various app
 * initialization operations are performed.
 */
public class SplashActivity extends Activity {

    private static final String LOG_TAG = SplashActivity.class.getSimpleName();
    protected static final String COOKIE_KEY = "cookie";
    protected static final String CRUMB_KEY = "crumb";
    private CookieHelper mCookieHelper;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Log.d(LOG_TAG, "onCreate");

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);

        Toast.makeText(getApplicationContext(), "Loading...", Toast.LENGTH_SHORT).show();

        // attempt to get cookie from Yahoo
        mCookieHelper = new CookieHelper();
        final RequestManager requestManager = new RequestManager();
        mCookieHelper.getCookie(getApplicationContext(), requestManager,  new RequestListener() {

            @Override
            public void onRequestComplete(final String response) {

                int index = response.lastIndexOf("CrumbStore");
                if (index != -1) {
                    Log.e("CRUMB", "found crumb: " + response.substring(index+22, index+33));
                    Log.e("COOKIE", "found cookie: " + requestManager.cookieManager.getCookieStore().getCookies().get(0).toString());

                    // Save cookie & crumb to var
                    mCookieHelper.setCrumb(response.substring(index+22, index+33)); // crumb
                    mCookieHelper.setCookie(requestManager.cookieManager.getCookieStore().getCookies().get(0).toString()); // cookie

                    // Sometimes the crumb contains escape chars, will need to figure out how to check for those and to escape them.
                    //StringEscapeUtils.unescapeJava(response.substring(index+22, index+33));

                    // Go to main activity when cookie has been loaded.
                    goMain(SplashActivity.this);
                }
            }
        });

    }

    /** Go to the main activity. */
    private void goMain(final Activity callingActivity) {
        Intent intent = new Intent(callingActivity, MainActivity.class).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intent.putExtra(COOKIE_KEY, mCookieHelper.getCookie());
        intent.putExtra(CRUMB_KEY, mCookieHelper.getCrumb());
        callingActivity.startActivity(intent);
        callingActivity.finish();
    }

}
